name: CI (German)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Build German PDF and upload as an artifact
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: IV_Indicators_User_Manual_de.tex
          texlive_version: latest
          extra_system_packages: coreutils icu inkscape
      - name: Upload the artifact
        uses: actions/upload-artifact@v4
        with:
          name: IV_Indicators_User_Manual_de
          path: |
            README.md
            IV_Indicators_User_Manual_de.pdf
  verify:
    name: Verify German PDF/A
    runs-on: ubuntu-latest
    needs: build
    container: { image: ghcr.io/jdujava/cuni-thesis-validator }
    steps:
      - name: Get the PDF file from the artifact
        uses: actions/download-artifact@v4
      - name: Verify the PDF file with VeraPDF
        run: verify IV_Indicators_User_Manual_de/*.pdf | tee /dev/stderr | grep -qE 'nonCompliant="0" failedJobs="0"'
